FROM golang:1.22-alpine3.20 AS builder
WORKDIR /app/image_service
COPY image_service/go.mod image_service/go.sum ./
# common/go.sum may not exist
COPY common/go.mod common/go.su[m] ../common/
RUN go mod download
COPY common/. ../common
COPY image_service/. .
RUN go build -o main cmd/grpc/main.go

FROM alpine:3.20
WORKDIR /app/image_service
COPY --from=builder /app/image_service/main .
EXPOSE 50055
CMD [ "./main"]